m23/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('m23_app.urls')),
]

m23_app/urls.py
from django.urls import path
from . import views

app_name = 'm23_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_order', views.new_order, name='new_order'),
    path('services', views.services, name='services'),
    path('about_us', views.about_us, name='about_us'),
    path('contacts', views.contacts, name='contacts'),
]

m23_app/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Order(models.Model):
    '''Модель заказа.'''
    name = models.CharField(max_length=30)
    phone_number = PhoneNumberField(blank=True)
    car_model = models.CharField(max_length=30)
    question = models.TextField(max_length=500)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''Возвращает строковое представление модели.'''
        return f' {self.phone_number} | {self.name[:15]} | {self.car_model[:15]}'

m23_app/views.py
from django.shortcuts import render, redirect
from .models import Order
from bot import send_telegram_message
from .recaptcha import create_assessment
import os

credential_path = os.environ.get("CREDENTIAL_PATH")
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = credential_path


def index(request):
    return render(request, 'm23_app/index.html')


def services(request):
    return render(request, 'm23_app/services.html')


def about_us(request):
    return render(request, 'm23_app/about_us.html')


def contacts(request):
    return render(request, 'm23_app/contacts.html')


def new_order(request):
    if request.method == 'POST':
        recaptcha_token = request.POST.get('g-recaptcha-response')
        try:
            response = create_assessment(
                project_id=os.environ.get("PROJECT_ID"),
                recaptcha_key=os.environ.get("RECAPTCHA_PUBLIC_KEY"),
                token=recaptcha_token,
                recaptcha_action="login"
            )
        except:
            print('reCAPTCHA не пройдена.'
                  '\nОШИБКА при выполнении create_assessment.'
                  '\nВозможно не нажали "я не робот".')
            return render(request, 'm23_app/new_order.html')

        if response and response.risk_analysis.score < 0.9:
            print('reCAPTCHA пройдена')
            name = request.POST['name']
            phone_number = request.POST['phone_number']
            car_model = request.POST['car_model']
            question = request.POST['question']
            order = Order.objects.create(name=name.title(),
                                         phone_number=phone_number,
                                         car_model=car_model,
                                         question=question)
            order.date_add = order.date_add.strftime("%d/%m/%Y . %H:%M")
            print('Заказ создан')
            send_telegram_message(order)
            return redirect('m23_app:index')
        else:
            print('reCAPTCHA не пройдена')
            return render(request, 'm23_app/index.html')
    else:
        return render(request, 'm23_app/new_order.html')

m23_app/templates/m23_app/about_us.html
{% extends "m23_app/base.html" %}

{% block content %}
<div class="pb-2 mb-2 border-bottom">
    <a class="btn btn-dark" style="color:#DAA520" href="{% url 'm23_app:new_order' %}">
        ЗАПИСАТЬСЯ
    </a>
</div>

<div>
    <h4><a class="btn btn-dark btn-sm" href="{% url 'm23_app:index' %}">Назад</a></h4>
</div>
<br/>
<div class="card bg-dark">
    <div class="card-body">
        <h5 class="card-title nav-link text-light">M23 DETAILING</h5>
        <p class="card-text nav-link text-light">Cтраница в разработке . . .</p>
    </div>
</div>
{% endblock content %}

m23_app/templates/m23_app/base.html
<!doctype html>
<html lang="en">
<head>
    <title>M23 Detailing</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://www.google.com/recaptcha/enterprise.js?render='6LeagUgqAAAAANmi0JMWh041gqUVE4f8XCodNzaH'"
            async defer></script>
    <script>
        grecaptcha.ready(function() {
            grecaptcha.execute('6LeagUgqAAAAANmi0JMWh041gqUVE4f8XCodNzaH', {action: 'login'})
                .then(function(token) {
                   document.getElementById('my_form').submit();
                });
        });
    </script>

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body bgcolor="2F4F4F">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
    <div class="container-fluid">

        <a class="navbar-brand" style="color:#DAA520" href="{% url 'm23_app:index' %}">M23</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'm23_app:services' %}">
                        Услуги</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'm23_app:about_us' %}">
                        О нас</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'm23_app:contacts' %}">
                        Контакты</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'm23_app:new_order' %}">
                        Записаться</a>
                </li>
            </ul>
            <span class="navbar-text" style="color:#DAA520">
                    M23 DETAILING CENTER
                </span>
        </div>

    </div>
</nav>


<main class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}
        <h2>M23</h2>
        <h4>DETAILING CENTER | UFA</h4>
        {% endblock page_header %}
    </div>
    {% block content %}
    {% endblock content %}
</main>
</body>
</html>

m23_app/templates/m23_app/contacts.html
{% extends "m23_app/base.html" %}

{% block content %}
<div class="pb-2 mb-2 border-bottom">
    <a class="btn btn-dark" style="color:#DAA520" href="{% url 'm23_app:new_order' %}">
        ЗАПИСАТЬСЯ
    </a>
</div>

<div>
    <h4><a class="btn btn-dark btn-sm" href="{% url 'm23_app:index' %}">Назад</a></h4>
</div>
<br/>
<div class="card bg-dark">
    <div class="card-body">
        <h5 class="card-title nav-link text-light">НАШИ КОНТАКТЫ :</h5>
        <p class="nav-link text-light">Телефон : +7 962 533 0005</p>
        <p class="nav-link text-light">WhatsApp : +7 962 533 0005</p>
        <p class="nav-link text-light">Email : autoufa.detailing@gmail.com</p>
        <p class="nav-link text-light">г. Уфа : д. Суровка, ул. Виноградная, 1к3</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md">
            <p><a class="btn btn-outline-light btn-sm" href="https://go.2gis.com/ub4j0">
                Мы в 2ГИС</a>
            </p>
            <p><a class="btn btn-outline-light btn-sm" href="http://t.me/m23detailingufa">
                Telegram канал</a>
            </p>
            <p><a class="btn btn-outline-light btn-sm" href="https://t.me/m23_detaling_bot">
                Telegram бот</a>
            </p>
        </div>
        <div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d812.4930708389328!2d55.90711967742323!3d54.83132444042947!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1726737024254!5m2!1sru!2sru"
                    width="370"
                    height="300"
                    style="border:0;"
                    allowfullscreen=""
                    loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade">

            </iframe>
        </div>

    </div>
</div>
{% endblock content %}

m23_app/templates/m23_app/index.html
{% extends "m23_app/base.html" %}
{% block content %}
<div class="pb-2 mb-2 border-bottom">
    <a class="btn btn-dark" style="color:#DAA520" href="{% url 'm23_app:new_order' %}">ЗАПИСАТЬСЯ</a>
</div>
<h5><a class="btn btn-dark" href="{% url 'm23_app:services' %}">Услуги</a></h5>
<h5><a class="btn btn-dark" href="{% url 'm23_app:about_us' %}">О нас</a></h5>
<h5><a class="btn btn-dark" href="{% url 'm23_app:contacts' %}">Контакты</a></h5>
{% endblock content %}

m23_app/templates/m23_app/new_order.html
{% extends "m23_app/base.html" %}

{% block content %}

<div>
    <h4><a class="btn btn-dark btn-sm" href="{% url 'm23_app:index' %}">Назад</a></h4>
</div>
<br/>
<small>
    <div class="card bg-dark">
        <div class="card-header text-white bg-dark">
            ЗАПОЛНИТЕ АНКЕТУ
        </div>
        <div class="card-body">
            <form action="{% url 'm23_app:new_order' %}" method="POST">
                {% csrf_token %}
                <div>
                    <label for="name"></label>
                    <p class="nav-link text-light">Ваше имя :</p>
                    <input type="text"
                           name="name"
                           autocapitalize="words"
                           title="Введите своё имя"
                           maxlength="30"
                           required>
                </div>
                <div>
                    <label for="phone_number"></label>
                    <p class="nav-link text-light"> Телефон (+7 _________ ) :</p>
                    <input type="tel"
                           name="phone_number"
                           maxlength="10"
                           pattern="[0-9]{10}"
                           title="Введите 10 цифр номера (без '+7' или '8')"
                           required>
                </div>
                <div>
                    <label for="car_model"></label>
                    <p class="nav-link text-light">Марка и модель авто : </p>
                    <input type="text"
                           name="car_model"
                           title="Введите название вашего автомобиля"
                           maxlength="30"
                           required>
                </div>
                <div><label for="question"></label>
                    <p class="nav-link text-light">Какой вопрос :</p>
                    <textarea type="text"
                              style="width: 350px; height: 60px;"
                              name="question"
                              title="Введите интересующую вас услугу или вопрос"
                              maxlength="300"
                              required></textarea>
                </div>
                <div>
                    <br/>
                    <div class="g-recaptcha"
                         data-sitekey="6LeagUgqAAAAANmi0JMWh041gqUVE4f8XCodNzaH"
                         data-action="login"
                         required></div>
                </div>
                <div>
                    <br/>
                    <button name="submit" class="btn btn-outline-warning">
                        Подтвердить запись
                    </button>
                </div>
            </form>
        </div>
    </div>
</small>
{% endblock content %}

m23_app/templates/m23_app/services.html
{% extends "m23_app/base.html" %}

{% block content %}
<div class="pb-2 mb-2 border-bottom">
    <a class="btn btn-dark" style="color:#DAA520" href="{% url 'm23_app:new_order' %}">
    ЗАПИСАТЬСЯ
    </a>
</div>

<div>
    <h4><a class="btn btn-dark btn-sm" href="{% url 'm23_app:index' %}">Назад</a></h4>
</div>
<br/>
<div class="card bg-dark">
    <div class="card-body">
        <h5 class="card-title nav-link text-light">НАШИ УСЛУГИ :</h5>
        <p class="card-text nav-link text-light">- Тонирование</p>
        <p class="card-text nav-link text-light">- Бронирование</p>
        <p class="card-text nav-link text-light">- Химчистка</p>
        <p class="card-text nav-link text-light">- Оклейка кузова </p>
        <p class="card-text nav-link text-light">- Антихром</p>
        <p class="card-text nav-link text-light">- Смена цвета</p>
        <p class="card-text nav-link text-light">- Полировка</p>
        <p class="card-text nav-link text-light">- Керамика / Жидкое стекло</p>
        <p class="card-text nav-link text-light">- Установка доп. оборудования</p>
        <p class="card-text nav-link text-light">- Шумоизоляция</p>
    </div>
</div>
{% endblock content %}